backend/src/Entity/Conge.php
<?php

namespace App\Entity;

use App\Repository\CongeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CongeRepository::class)]
class Conge
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut_con = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin_con = null;

    #[ORM\Column]
    private ?int $duree_conge = null;

    #[ORM\ManyToOne(inversedBy: 'conges')]
    private ?User $User = null;

    #[ORM\Column(length: 255)]
    private ?string $reason = null;

    #[ORM\Column(length: 15)]
    private ?string $progress = null;

    #[ORM\Column(length: 255)]
    private ?string $department = null;

    #[ORM\Column(length: 255)]
    private ?string $fullname = null;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebutCon():string
    {
        return $this->date_debut_con->format("Y-m-d");
    }

    public function setDateDebutCon(\DateTimeInterface $date_debut_con): static
    {
        $this->date_debut_con = $date_debut_con;

        return $this;
    }

    public function getDateFinCon():string
    {
        return $this->date_fin_con->format("Y-m-d");
    }

    public function setDateFinCon(\DateTimeInterface $date_fin_con): static
    {
        $this->date_fin_con = $date_fin_con;

        return $this;
    }

    public function getDureeConge(): ?int
    {
        return $this->duree_conge;
    }

    public function setDureeConge(int $duree_conge): static
    {
        $this->duree_conge = $duree_conge;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(string $reason): static
    {
        $this->reason = $reason;

        return $this;
    }

    public function getProgress(): ?string
    {
        return $this->progress;
    }

    public function setProgress(string $progress): static
    {
        $this->progress = $progress;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(string $department): static
    {
        $this->department = $department;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): static
    {
        $this->fullname = $fullname;

        return $this;
    }

}

backend/src/Form/CongeType.php
<?php

namespace App\Form;

use App\Entity\Conge;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CongeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut_con')
            ->add('date_fin_con')
            ->add('duree_conge')
            ->add('reason')
            ->add('progress')
            ->add('department')
            ->add('fullname')
            ->add('User', EntityType::class, [
                'class' => User::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Conge::class,
        ]);
    }
}

backend/src/Controller/CongeController.php
<?php

namespace App\Controller;

use App\Entity\Conge;
use App\Form\CongeType;
use App\Repository\CongeRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use mysql_xdevapi\Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/conge')]
class CongeController extends AbstractController
{

    private $userRepository;
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    #[Route('/', name: 'app_conge_index', methods: ['GET'])]
    public function index(CongeRepository $congeRepository): JsonResponse
    {
        $data = $congeRepository->findAll();
        $jsonData = $this->serialize($data);
        return new JsonResponse($jsonData);
    }
    #[Route('/only/{id}', name: 'app_conge_only', methods: ['GET'])]
    public function allById(CongeRepository $congeRepository,int $id): JsonResponse
    {

        try {
            $user = $this->userRepository->findOneBy(['id'=>$id]);
            $data = $user->getConges();
            $jsonData = $this->serialize($data);
        }catch (\Exception $e){
            return new JsonResponse(["error"=>$e->getMessage()]);
    }
        return new JsonResponse($jsonData);
    }
    private function serialize($conges): array
    {
        // Serialize users to an array or customize the serialization as needed
        $data = [];

        foreach ($conges as $conge) {
            $data[] = [
                'id'=>$conge->getId(),
                'fullname' => $conge->getFullname(),
                'reason' => $conge->getReason(),
                'department'=>$conge->getDepartment(),
                'sdate'=>$conge->getDateDebutCon(),
                'fdate'=>$conge->getDateFinCon(),
                'progress'=>$conge->getProgress()

            ];
        }
        return $data;
    }
    #[Route('/new', name: 'app_conge_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): JsonResponse
    {

        $data = json_decode($request->getContent(), true);
        $user = $this->userRepository->findOneBy(['id'=>$data['id']]);
        $conge = new Conge();
        $sdate = \DateTime::createFromFormat("Y-m-d", $data['sdate']);
        $fdate = \DateTime::createFromFormat("Y-m-d", $data['fdate']);
                $conge->setUser($user);
                $conge->setFullname($data['fullname']);
                $conge->setReason($data['reason']);
                $conge->setDepartment($data['department']);
                $conge->setDateDebutCon($sdate);
                $conge->setDateFinCon($fdate);
                $conge->setDureeConge(10);
                $conge->setProgress($data['progress']);
            $entityManager->persist($conge);
            $entityManager->flush();
        return new JsonResponse(['state'=>'S']);

        }



    #[Route('/{id}', name: 'app_conge_show', methods: ['GET'])]
    public function show(Conge $conge): Response
    {
        return $this->render('conge/show.html.twig', [
            'conge' => $conge,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_conge_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Conge $conge, EntityManagerInterface $entityManager): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $conge->setProgress($data['progress']);
        $entityManager->flush();
        return new JsonResponse(['message'=>'S']);

    }

    #[Route('/{id}', name: 'app_conge_delete', methods: ['POST'])]
    public function delete(Request $request, Conge $conge, EntityManagerInterface $entityManager): JsonResponse
    {

            $entityManager->remove($conge);
            $entityManager->flush();


        return new JsonResponse(['info'=>'D']);
    }
}

backend/templates/conge/_delete_form.html.twig
<form method="post" action="{{ path('app_conge_delete', {'id': conge.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conge.id) }}">
    <button class="btn">Delete</button>
</form>

backend/templates/conge/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

backend/templates/conge/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Conge{% endblock %}

{% block body %}
    <h1>Edit Conge</h1>

    {{ include('conge/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_conge_index') }}">back to list</a>

    {{ include('conge/_delete_form.html.twig') }}
{% endblock %}

backend/templates/conge/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conge index{% endblock %}

{% block body %}
    <h1>Conge index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut_con</th>
                <th>Date_fin_con</th>
                <th>Duree_conge</th>
                <th>Reason</th>
                <th>Progress</th>
                <th>Department</th>
                <th>Fullname</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for conge in conges %}
            <tr>
                <td>{{ conge.id }}</td>
                <td>{{ conge.dateDebutCon ? conge.dateDebutCon|date('Y-m-d') : '' }}</td>
                <td>{{ conge.dateFinCon ? conge.dateFinCon|date('Y-m-d') : '' }}</td>
                <td>{{ conge.dureeConge }}</td>
                <td>{{ conge.reason }}</td>
                <td>{{ conge.progress }}</td>
                <td>{{ conge.department }}</td>
                <td>{{ conge.fullname }}</td>
                <td>
                    <a href="{{ path('app_conge_show', {'id': conge.id}) }}">show</a>
                    <a href="{{ path('app_conge_edit', {'id': conge.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_conge_new') }}">Create new</a>
{% endblock %}

backend/templates/conge/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Conge{% endblock %}

{% block body %}
    <h1>Create new Conge</h1>

    {{ include('conge/_form.html.twig') }}

    <a href="{{ path('app_conge_index') }}">back to list</a>
{% endblock %}

backend/templates/conge/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conge{% endblock %}

{% block body %}
    <h1>Conge</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ conge.id }}</td>
            </tr>
            <tr>
                <th>Date_debut_con</th>
                <td>{{ conge.dateDebutCon ? conge.dateDebutCon|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin_con</th>
                <td>{{ conge.dateFinCon ? conge.dateFinCon|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Duree_conge</th>
                <td>{{ conge.dureeConge }}</td>
            </tr>
            <tr>
                <th>Reason</th>
                <td>{{ conge.reason }}</td>
            </tr>
            <tr>
                <th>Progress</th>
                <td>{{ conge.progress }}</td>
            </tr>
            <tr>
                <th>Department</th>
                <td>{{ conge.department }}</td>
            </tr>
            <tr>
                <th>Fullname</th>
                <td>{{ conge.fullname }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_conge_index') }}">back to list</a>

    <a href="{{ path('app_conge_edit', {'id': conge.id}) }}">edit</a>

    {{ include('conge/_delete_form.html.twig') }}
{% endblock %}